[ui]
scale=1.0
maximize=1
#layout=h(60,v(75,Source,Console),v(50,t(Exe,Breakpoints,Commands,Struct),t(Stack,Files,Registers,Data,Thread))))
layout=v(60,h(60,Source,v(50,t(Exe,Breakpoints,Commands,Struct),t(Stack,Files,Thread,CmdSearch))),h(50,Console,t(Watch,Locals,Registers,Data)))

