#!/bin/sh

CODE=""
if [ -x "/usr/bin/codium" ]; then
    CODE="codium"
fi
if [ -x "/usr/bin/code" ]; then
    CODE="code"
fi

[ -z "$CODE" ] && \
    echo "Error: vscodium or vscode not installed" && \
    exit 1

exec "$CODE" "$@"

