#!/bin/sh

# Create a blank POSIX shell script

usage_and_die() {
    echo "Usage: create-shell-script <filename>"    
    exit 1
}

# Error-checking
[ "$#" -lt "1" ] && \
    echo "Error: No filename entered" && \
    usage_and_die

# If file already exists just edit it, don't create
[ -f "$@" ] && \
    "$EDITOR" "$@" &&
    exit "$?"

printf "#!/bin/sh\\n\\n" > "$@"
chmod +x "$@"
"$EDITOR" "$@"
