#!/bin/sh

BACKUP_DIR="$HOME/Documents/rm2/backup/"
mkdir -p "$BACKUP_DIR"

rsync -e "ssh -oPubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa" -ruzP --delete-after root@10.11.99.1:/home/root/.local/share/remarkable/xochitl/ "$BACKUP_DIR"
#scp -oHostKeyAlgorithms=+ssh-rsa -r root@10.11.99.1:/home/root/.local/share/remarkable/xochitl/ "$BACKUP_DIR"
echo Done.
