#!/bin/sh

! which magick >/dev/null 2>&1 && \
    echo "Error: ImageMagick \"magick\" bin not installed" >&2 && \
    exit 1

[ -z "$1" ] && \
    echo "Error: Please provide a wallpaper image as first argument" && \
    exit 1

set -e # Exit on error

echo Converting file
magick "$1" -resize 1404x1872\! -colorspace Gray "$1"-converted.png

echo Setting Wallpaper
scp -q -oPubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa "$1"-converted.png root@10.11.99.1:/usr/share/remarkable/suspended.png
rm "$1"-converted.png

echo Done.
echo Please reboot remarkable for wallpaper to take effect.

