#!/bin/sh

DIR="."
[ -n "$1" ] && DIR="$1"

# Find all files and shred
files=$(find "$DIR" -type f)
[ -n "$files" ] && \
    echo "$files" | xargs shred -fuzv -n 48

# Find all now empty directories and remove them
find "$DIR" -type d -empty -delete

